
name: Deploy TamaTown Central to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore H3-Projekt.sln
    
    - name: Build solution
      run: dotnet build H3-Projekt.sln --configuration Release --no-restore
    
    - name: Run tests (if any)
      run: dotnet test H3-Projekt.sln --no-restore --verbosity normal --configuration Release
      continue-on-error: true
    
    # Debug: Check project structure
    - name: List project structure
      run: |
        echo "Root directory contents:"
        ls -la
        echo "API directory contents:"
        ls -la API/
        echo "Blazor directory contents:"
        ls -la Blazor/
    
    # Build and publish API with verbose output
    - name: Publish TamaTown API
      run: |
        echo "Publishing API project..."
        dotnet publish API/API.csproj --configuration Release --output ./api-publish --verbosity normal
        echo "Publish command completed with exit code: $?"
    
    # Verify API publish output (only if previous step succeeded)
    - name: List API publish contents
      run: |
        if [ -d "./api-publish" ]; then
          echo "API publish directory exists:"
          ls -la ./api-publish/
        else
          echo "API publish directory does not exist"
          echo "Current directory contents:"
          ls -la
        fi
    
    # Build and publish Blazor with verbose output
    - name: Publish TamaTown Blazor App
      run: |
        echo "Publishing Blazor project..."
        dotnet publish Blazor/Blazor.csproj --configuration Release --output ./blazor-publish --verbosity normal
        echo "Publish command completed with exit code: $?"
    
    # Verify Blazor publish output (only if previous step succeeded)
    - name: List Blazor publish contents
      run: |
        if [ -d "./blazor-publish" ]; then
          echo "Blazor publish directory exists:"
          ls -la ./blazor-publish/
        else
          echo "Blazor publish directory does not exist"
          echo "Current directory contents:"
          ls -la
        fi
    
    # Deploy API to Azure App Service (only if publish succeeded)
    - name: Deploy API to Azure App Service
      if: success()
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TamaTownCentralAPI'
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: './api-publish'
    
    # Deploy Blazor to Azure App Service (only if publish succeeded)
    - name: Deploy Blazor to Azure App Service
      if: success()
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TamaTownCentral'
        publish-profile: ${{ secrets.AZURE_BLAZOR_PUBLISH_PROFILE }}
        package: './blazor-publish'
