name: Deploy TamaTown Central to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore H3-Projekt.sln
    
    - name: Build solution
      run: dotnet build H3-Projekt.sln --configuration Release --no-restore
    
    - name: Run tests (if any)
      run: dotnet test H3-Projekt.sln --no-restore --verbosity normal --configuration Release
      continue-on-error: true
    
    # Debug: Check project structure
    - name: List project structure
      run: |
        echo "Root directory contents:"
        ls -la
        echo "API directory contents:"
        ls -la API/
        echo "Blazor directory contents:"
        ls -la Blazor/
    
    # Build and publish API with verbose output
    - name: Publish TamaTown API
      run: |
        echo "Publishing API project..."
        dotnet publish API/API.csproj --configuration Release --output ./api-publish --verbosity normal
        echo "Publish command completed with exit code: $?"
    
    - name: List root directory contents (for debugging API publish)
      run: |
        echo "Listing contents of workspace root (${{ github.workspace }}):"
        ls -la ${{ github.workspace }}
        if [ -d "${{ github.workspace }}/api-publish" ]; then
          echo "Found api-publish at root!"
        else
          echo "api-publish NOT found at root."
        fi

    - name: List API directory contents (to find the API publish folder)
      run: |
        echo "Listing contents of API directory (${{ github.workspace }}/API):"
        ls -la ${{ github.workspace }}/API/
        if [ -d "${{ github.workspace }}/API/api-publish" ]; then
          echo "Found api-publish inside API directory!"
        else
          echo "api-publish NOT found inside API directory."
        fi
    
    # Build and publish Blazor with verbose output
    - name: Publish TamaTown Blazor App
      run: |
        echo "Publishing Blazor project..."
        dotnet publish Blazor/Blazor.csproj --configuration Release --output ./blazor-publish --verbosity normal
        echo "Publish command completed with exit code: $?"
    
    - name: List root directory contents (for debugging Blazor publish)
      run: |
        echo "Listing contents of workspace root (${{ github.workspace }}):"
        ls -la ${{ github.workspace }}
        if [ -d "${{ github.workspace }}/blazor-publish" ]; then
          echo "Found blazor-publish at root!"
        else
          echo "blazor-publish NOT found at root."
        fi

    - name: List Blazor directory contents (to find the Blazor publish folder)
      run: |
        echo "Listing contents of Blazor directory (${{ github.workspace }}/Blazor):"
        ls -la ${{ github.workspace }}/Blazor/
        if [ -d "${{ github.workspace }}/Blazor/blazor-publish" ]; then
          echo "Found blazor-publish inside Blazor directory!"
        else
          echo "blazor-publish NOT found inside Blazor directory."
        fi
    
    # Deploy API to Azure App Service (only if publish succeeded)
    - name: Deploy API to Azure App Service
      if: success()
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TamaTownCentralAPI'
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/API/api-publish 
        slot-name: production
    
    # Deploy Blazor to Azure App Service (only if publish succeeded)
    - name: Deploy Blazor to Azure App Service
      if: success()
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TamaTownCentral'
        publish-profile: ${{ secrets.AZURE_BLAZOR_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/Blazor/blazor-publish
